ai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from browser.api import BrowserRouterRegistry
from .customizations import AdminPanelCustomization
from home.views import updateAssignedReport, saveConnectionsData,\
    dagScheduler, updateConnectionData, getConnectionData,\
    deleteConnectionData, getConnections, addassign_report,\
    getCreationReportData, getAssignedReportData, deleteCreationReport,\
    deleteAssignedReport, add_report, assign_report_data, save_report,\
    loginuser, home, logoutuser, pysql_execution, python_execution,\
    sql_execution, report_creation, reportLineItem, getReportItemData,\
    updateReportItem, deleteReportItem, createReportItem
from browser.views import file_upload, profiling, finish, sources,\
    deletesource, conversion, runconversion, pushtomemory
from django.contrib.auth.decorators import login_required
from home.api import ActivityRouterRegistry
from sparkplug.cycle import fire
from utils.autostart import Ignite

admin = AdminPanelCustomization.headersettings(admin)
browserrouter = BrowserRouterRegistry.buildrouters()
activityrouter = ActivityRouterRegistry.buildrouters()

# if Ignite.all() is True:
#     print('INFO: Sources added to memory')
# else:
#     print("WARNING: No sources to add to memory. If that's not whats intended please contact support.")

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include(browserrouter.urls)),
    # url(r'^', include(activityrouter.urls)),
    url(r'^api/v1/query', fire),
    url(r'^browser/', include('browser.urls')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
    url(r'^home/$', login_required(home), name="home"),
    url(r'^sources/$', login_required(sources), name="sources"),
    url(r'^data/conversion/$', login_required(conversion), name="conversion"),
    url(
        r'^data/runconversion/(?P<id>[^\/]*)/$',
        login_required(runconversion),
        name='runconversion'
    ),
    url(
        r'^data/memory/(?P<id>[^\/]*)/$',
        login_required(pushtomemory),
        name='pushtomemory'
    ),
    url(
        r'^manager/fileupload/',
        login_required(file_upload),
        name='file_upload'
    ),
    url(
        r'^manager/profiling/(?P<id>[^\/]*)/$',
        login_required(profiling),
        name='profiling'
    ),
    url(
        r'^manager/finish/(?P<id>[^\/]*)/$',
        login_required(finish),
        name='finish'
    ),
    url(
        r'^manager/deletesource/(?P<id>[^\/]*)/$',
        login_required(deletesource),
        name='deletesource'
    ),
    url(r'^accounts/login/$', loginuser),
    url(r'^accounts/logout/$', logoutuser),
    url(r'^pysql/$', login_required(pysql_execution), name="pysql_execution"),
    url(
        r'^python_execution/$',
        login_required(python_execution),
        name="python_execution"
    ),
    url(
        r'^sql_execution/$',
        login_required(sql_execution),
        name="sql_execution"
    ),
    url(
        r'^report-creation/$',
        login_required(report_creation),
        name="report_creation"
    ),
    url(
        r'^deleteCreationReport/$',
        login_required(deleteCreationReport),
        name="deleteCreationReport"
    ),
    url(
        r'^getCreationReportData/$',
        login_required(getCreationReportData),
        name="getCreationReportData"
    ),
    url(r'^save_report/$', login_required(save_report), name="save_report"),
    url(
        r'^assign_reports/$',
        login_required(assign_report_data),
        name="assign_report_data"
    ),
    url(r'^add_report/$', login_required(add_report), name="add_report"),
    url(
        r'^deleteAssignedReport/$',
        login_required(deleteAssignedReport),
        name="deleteAssignedReport"
    ),
    url(
        r'^getAssignedReportData/$',
        login_required(getAssignedReportData),
        name="getAssignedReportData"
    ),
    url(
        r'^updateAssignedReport/$',
        login_required(updateAssignedReport),
        name="updateAssignedReport"
    ),
    url(
        r'^addassign_report/$',
        login_required(addassign_report),
        name="addassign_report"
    ),
    url(
        r'^connections/$',
        login_required(getConnections),
        name="getConnections"
    ),
    url(
        r'^saveConnectionsData/$',
        login_required(saveConnectionsData),
        name="saveConnectionsData"
    ),
    url(
        r'^deleteConnectionData/$',
        login_required(deleteConnectionData),
        name="deleteConnectionData"
    ),
    url(
        r'^getConnectionData/$',
        login_required(getConnectionData),
        name="getConnectionData"
    ),
    url(
        r'^updateConnectionData/$',
        login_required(updateConnectionData),
        name="updateConnectionData"
    ),
    url(r'^dagScheduler/$', login_required(dagScheduler), name="dagScheduler"),
    url(
        r'^report-line-item/$',
        login_required(reportLineItem),
        name="reportLineItem"
    ),
    url(
        r'^getReportItemData/$',
        login_required(getReportItemData),
        name="getReportItemData"
    ),
    url(
        r'^updateReportItem/$',
        login_required(updateReportItem),
        name="updateReportItem"
    ),
    url(
        r'^deleteReportItem/$',
        login_required(deleteReportItem),
        name="deleteReportItem"
    ),
    url(
        r'^createReportItem/$',
        login_required(createReportItem),
        name="createReportItem"
    ),
    # API URLS
    url(r'^api/', include('reports_apis.urls')),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),

]

browser/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
    url(r'^$', index, name="browser-index"),
]

browser/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


def generate_filename(instance, filename):
    print(str(instance))
    url = "data/users/{0}/{1}".format(instance.user.username, filename)
    return url


class Source(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    table = models.CharField(max_length=250)
    docfile = models.FileField(upload_to=generate_filename, null=True)
    file_location = models.TextField(null=True)
    ods_file_location = models.TextField(null=True)
    identifier = models.UUIDField(default=uuid.uuid1())
    in_memory = models.BooleanField(default=False)
    analysed = models.BooleanField(default=False)
    extension = models.CharField(max_length=10)
    user = models.ForeignKey(User)

    class Meta:
        permissions = (
            ("read_access_source", "Read Access to Source"),
        )

    def __str__(self):
        return self.table


class FieldType(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    field_type = models.CharField(max_length=50)

    def __str__(self):
        return self.field_type


class DataType(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    data_type = models.CharField(max_length=50)

    def __str__(self):
        return self.data_type


class Feature(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    field_name = models.CharField(max_length=100)
    density = models.DecimalField(decimal_places=2, max_digits=5)
    source_link = models.ForeignKey(Source, on_delete=models.CASCADE)
    fieldtype_link = models.ForeignKey(FieldType)
    datatype_link = models.ForeignKey(DataType)

    class Meta:
        permissions = (
            ("read_access_feature", "Read Access to feature"),
        )

    def __str__(self):
        return "{0} {1}".format(self.source, self.field_name)

browser/forms.py
from django import forms
from .models import Source
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class SourceForm(forms.Form):
    table = forms.CharField(max_length=250)
    docfile = forms.FileField()

webapp/templates/browser/conversion.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Sources
{% endblock %}
{% block test %}
        <div class="container-fluid1 wholeTilesMargin">
            <div class="row main_content_row">
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white o-hidden h-100 block_cards_header bgColorUnset  layoutBorderColor ">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <span class="sprite bg-icon_calculator1"></span>
                            </div>
                            <div class="mr-5"><font class="showTotalSources">{{ totalsources }}</font>
                                <p>Sources</p>
                            </div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="/sources/">
                            <span class="float-left">View Details</span>
                            <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                      </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white o-hidden h-100 block_cards_header layoutBorderColor">
                        <div class="card-body active">
                            <div class="card-body-icon">
                                <span class="sprite bg-icon_sim"></span>
                            </div>
                            <div class="mr-5"><font class="showTotalSources">{{ sinmemory }}</font>
                                <p>Sources In Memory</p>
                            </div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1 active" href="/data/conversion/">
                            <span class="float-left">View Details</span>
                            <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                      </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white o-hidden h-100 block_cards_header layoutBorderColor">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <span class="sprite bg-icon_report"></span>
                            </div>
                            <div class="mr-5"><font class="showTotalSources">{% if z %}{{z}}{% else %} 0 {% endif %}</font>
                                <p>Reports</p>
                            </div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="/report-creation/">
                            <span class="float-left">View Details</span>
                            <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                      </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white o-hidden h-100 block_cards_header layoutBorderColor">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <span class="sprite bg-icon_ticket"></span>
                            </div>
                            <div class="mr-5"><font class="showTotalSources"></font>
                                <p>Assign Reports</p>
                            </div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="/assign_reports/">
                            <span class="float-left">View Details</span>
                            <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                      </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
{% block pagecontent %}
<div class="container-fluid main_content_container">
    <div class="row main_content_row">
        <div class="activity_feed_table col">
            <div style="margin-bottom:40px;">
              <h4>Conversions
                  <button class="btn commonButtonColor pull-right" data-toggle="modal" data-target="#sourceUploadModal" type="button"><i class="fa fa-plus" style="margin-right: 8px;" aria-hidden="true"></i>Create a new Source</button>
              </h4>
            </div>
            <table class="row-border table-responsive compact" id="ConversionDataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th style="white-space: nowrap; padding-left: 0px;">Table Name</th>
                  <th>Stored Location</th>
                  <th>ODS Location</th>
                  <th>In Memory</th>
                  <th>Analysed</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for key, values in data.items %}
              <tr>
                <td><a class="commonLinkColor source_conversion_modal" href="#" data-id="{{ key }}">{{values.table}}</a></td>
                <td>{{values.docfile}}</td>
                <td>{{values.ods}}</td>
                <td>
                    <form action="/data/memory/{{key}}/"
                          method="post"
                          data-ajax="false"
                          enctype="multipart/form-data">{% csrf_token %}
                        <center >
                            <label class="checkbox-inline testclass">
                              <input
                                      id="i!{{key}}"
                                      name="i_{{key}}"
                                      type="checkbox"
                                     data-toggle="toggle"
                                     data-size='small'
                                     data-width="100"
                                     data-on='Memory'
                                     data-off='<i class="fa fa-hdd-o" aria-hidden="true"></i> Disc'
                                     {{values.memory}}
                                     onchange="this.form.submit()">
                            </label>
                        </center>
                    </form>
                </td>
                </td>
                <td>
                    <form>{% csrf_token %}
                        <center id="source_analyzed_center">
                            <label class="checkbox-inline">
                              <input
                                      id="a!{{key}}"
                                      name="a_{{key}}"
                                      type="checkbox"
                                     data-toggle="toggle"
                                     data-size="small"
                                     data-width="150"
                                     data-on='Analysed <i class="fa fa-check" aria-hidden="true"></i>'
                                     data-off='Start Analysis'
                                     {{values.analysed}}
                                      disabled
                                     >
                            </label>
                        </center>
                    </form>
                </td>
                <td>
                    <a class="btn btn-primary" style="padding:2px 10px 2px 10px;color:white;" data-toggle="modal" data-target="#modal{{key}}">
                        <i class="fa fa-spinner" aria-hidden="true"></i>
                    </a>
                </td>
              </tr>

                <div id="modal{{key}}" class="modal fade" role="dialog">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                          <h4 class="modal-title pull-left">Optimized source conversion</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">
                          <p> Are you sure you want to convert the <b>{{values.table}}</b> dataset into flair optimized source?</p>
                          <center>
                            <i id="icon{{key}}" class="" aria-hidden="true"></i>
                          </center>
                      </div>
                        <form action="/data/runconversion/{{key}}/" method="post" data-ajax="false" enctype="multipart/form-data">{% csrf_token %}
                          <div class="modal-footer">
                              <button id="key_{{key}}" type="submit" class="btn btn-primary">Yes</button>
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </form>
                    </div>
                  </div>
                </div>

                {% endfor %}
              </tbody>
            </table>
            <div id="modal_spinner" class="modal fade" role="dialog">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                          <h4 class="modal-title pull-left">Source management</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">

                          <center>
                              <p> Performing operation.....</p></br>
                            <i id="mem_spin" class="fa fa-spinner fa-pulse fa-5x ap-spinner-color" aria-hidden="true"></i>
                          </center>
                      </div>
                    </div>
                  </div>
                </div>

        </div>
    </div>
</div>


{% endblock %}
{% block lazyload %}
<script src="{% static 'js/conversion.controller.js' %}"></script>
{% endblock %}

webapp/templates/browser/file-upload.html
{% extends 'file-manager.html' %}
{% load staticfiles %}
{% block title %}
File Upload
{% endblock %}
{% block upload %}
<form class="form-horizontal" action="manager/fileupload/" method="post" data-ajax="false" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
              <label class="control-label col-sm-3" for="id_table">Source Name:</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" id="id_table" placeholder="Source Name" name="table">
              </div>
            </div>
              <div class="form-group">
              <label class="control-label col-sm-3" for="id_docfile">File Upload:</label>
              <div class="col-sm-9">
                <input type="file" size="60" class="btn btn-default" id="id_docfile" accept=".json,.csv" name="docfile">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="submit" class="btn btn-success">Upload file and continue <i class="fa fa-step-forward" aria-hidden="true"></i></button>
              </div>
            </div>
</form>
{% endblock %}

webapp/templates/browser/finish.html
<div class="col-md-12">
 <div class="btn-group-round">
    <button class="round-btn-1 active"></button>
    <hr>
    <button class="round-btn-2 active"></button>
    <hr>
    <button class="round-btn-3 active"></button>
 </div>
 <div class="btn-group-round" style="padding: 0 46px 0 42px;">
    <span style="float:left;">File Upload</span>
    <span >Profiling</span>
    <span style="float:right;" >Finishing</span>
 </div>
</div>
<hr>

<div class="row">
    <div class="col-md-12">
        <center>
            <h4>Summary</h4>
        </center>
    </div>
</div></br>
<div class="container">
    <h5><u>Source:</u></h5>
    <div class="row">
        <div class="col-md-3">
            <h6>Id</h6>
        </div>
        <div class="col-md-8">
            <a>{{ data.id }}</a>
        </div>
        <div class="col-md-1">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h6>Name</h6>
        </div>
        <div class="col-md-8">
            <a>{{ data.table }}</a>
        </div>
        <div class="col-md-1">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h6>File Location</h6>
        </div>
        <div class="col-md-8">
            <a>{{ data.docfile }}</a>
        </div>
        <div class="col-md-1">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h6>Analysed</h6>
        </div>
        <div class="col-md-8">
            <input type="checkbox" name="analysed" value="{{data.analysed}}" {{data.analysed}} disabled>
        </div>
        <div class="col-md-1">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h6>In Memory</h6>
        </div>
        <div class="col-md-8">
            <input type="checkbox" name="analysed" value="{{data.memory}}" {{data.memory}} disabled>
        </div>
        <div class="col-md-1">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h6>Extension</h6>
        </div>
        <div class="col-md-8">
            <a>{{data.extension}}</a>
        </div>
        <div class="col-md-1">
        </div>
    </div>
</div>
</br>
<div class="container">
<h5><u>Features:</u></h5>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
              <tr>
                <th>Name</th>
                  <th>id</th>
                <th>Density</th>
                <th>Field Type</th>
                <th>Data Type</th>
              </tr>
                {% for key, values in data.features.items %}
              <tr>
                <td>{{values.id}}</td>
                <td>{{key}}</td>
                <td>{{values.density}}%</td>
                <td>{{values.fieldtype}}</td>
                <td>{{values.datatype}}</td>
              </tr>
                {% endfor %}
            </table>
        </div>
    </div></br>

    
<form action="/manager/finish/{{data.id}}/" method="post">{% csrf_token %}
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
      <button type="submit" type="button" class="btn btn-primary">Next</button>
  </div>
</form>
    
</div>

webapp/templates/browser/profiling.html
{% load staticfiles %}
<div class="col-md-12">
    <div class="btn-group-round">
        <button class="round-btn-1 active"></button>
        <hr>
        <button class="round-btn-2 active"></button>
        <hr>
        <button class="round-btn-3"></button>
    </div>
    <div class="btn-group-round" style="padding: 0 46px 0 42px;">
        <span style="float:left;">File Upload</span>
        <span>Profiling</span>
        <span style="float:right;">Finishing</span>
    </div>
</div>
<hr>

<div class="container">
    <h3 style="margin: 0 0 6px -13px;">Source Metadata</h4>
<form class="form-horizontal" enctype="multipart/form-data" id="step_profiling_form">
   {% csrf_token %}
  
   <label style="margin: 0 0 6px -13px;" class="control-label" for="id_source" >Source Id:</label>
   <div class="form-group">
    <div class="row">      
      <div class="col-sm-9" style="padding: 0;">
        <input type="text" class="form-control" id="id_source" placeholder="Source Id" name="source" value="{{data.sourceid}}" readonly >
      </div>
    </div>
  </div>
   <label style="margin: 0 0 6px -13px;" class="control-label"  >Fields found:</label>
   {% for key, values in data.fields.items %}
   <div class="form-group">
    <div class="row">
      <div class="col-xs-4" style="margin: 0 10px 0 0px;">
        <input type="text" class="form-control" id="u!{{key}}" placeholder="{{ values.id }}" name="u!{{key}}" value="{{ values.id }}" readonly>
      </div>
      <div class="col-xs-3">
        <input type="text" class="form-control" id="n!{{key}}" placeholder="{{ key }}" name="field" value="{{ key }}" readonly>
      </div>
      <div class="col-sm-3" style="max-width: 18%;">
        {% for k, val1 in values.fieldtype.items %}
        <fieldset id="fs{{key}}">
           <input type="radio" name="f!{{key}}" value="{{k}}" {{ val1 }}> {{ k }} <br>
        </fieldset>
        {% endfor %}
      </div>
      <div class="col-xs-3">  
        <select class="form-control" name="d!{{key}}">
        {% for k, val2 in values.datatype.items %}
        <option value="{{k}}" {{val2}}>{{k}}</option>
        {% endfor %}
        </select>
      </div>
    </div>
  </div>

   {% endfor %}
  
   <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
      <button type="submit" type="button" class="btn btn-primary">Next</button>
  </div>
</form>
</div>
<script type="text/javascript">
   var a = {{data|safe}};
   console.log(a);
</script>
{% block lazyload %}
<script src="{% static 'js/conversion.source_form_wizard.js' %}"></script>
{% endblock %}